#include "Game.h"

#include "Core/Common/Vector3.h"
#include "Core/Graphics/GraphicsDevice.h"
#include "Core/Graphics/VertexTypes/VertexPosition.h"
#include "Core/Graphics/VertexTypes/VertexPositionLayout.h"

#include "Core/Components/RenderComponent.h"

#include <fmt/core.h>

void testFunc()
{
    fmt::print("Test!");
}

namespace Ceres
{
    Game::Game()
    {
    }

    Game::~Game()
    {
    }

    bool Game::Initialize()
    {
        InputHandler.BindInput(Button::Key_space, &testFunc);
        return true;
    }

    void Game::Load()
    {
        // Example for current mesh loading code:
        // Loads a cube!

        VertexPosition verts[] = {
            Vector3(-1, -1, 1), Vector3(-1, 1, 1), Vector3(1, 1, 1), Vector3(1, -1, 1),
            Vector3(-1, -1, -1), Vector3(-1, 1, -1), Vector3(1, 1, -1), Vector3(1, -1, -1)};
        unsigned int indices[] = {
            0, 1, 2, 0, 2, 3,
            4, 5, 6, 4, 6, 7,
            1, 2, 5, 2, 5, 6,
            0, 3, 4, 3, 4, 7,
            0, 1, 4, 1, 4, 5,
            2, 3, 6, 3, 6, 7
        };

        // Store the meshId, which is generated by whatever class
        // manages the mesh loading.
        // For now, that is just the GraphicsDevice
        uint8_t meshId = _graphicsDevice.LoadMesh(verts, VertexPositionLayout(), 8, indices, 36);

        // Transforms can be set from each individual aspect,
        // position/translation, rotation, and scale.
        // This avoids having to calculate reverse transform matrices
        // or trying to solve rotation angles from a matrix.
        _graphicsDevice.CreateRenderComponent(meshId).Transform.SetScale(Vector3(1, 4, 1));
        _graphicsDevice.CreateRenderComponent(meshId).Transform.SetPosition(Vector3(-10, 0, 0));
    }

    void Game::Update()
    {
    }

    void Game::Draw()
    {
         _graphicsDevice.Render();
    }
}